export interface MonsterDrop {
    itemId: string;
    chance: number; // 0~100%
}

export interface DroppedItem {
    item: import('../types').GameItem;
    quantity: number;
}

export interface MonsterData {
    name: string;
    emoji: string;
    imageUrl?: string;
    videoUrl?: string;
    level: number;
    hp: number;
    attack: number;
    isBoss: boolean;
    spawnChance: number; // 등장 확률 (0~100)
    drops: MonsterDrop[];
}

export interface DungeonData {
    id: number;
    name: string;
    levelRange: string; // "1~10" 형식
    minLevel: number;
    maxLevel: number;
    description: string;
    monsters: MonsterData[];
}

export type BattleState = 'idle' | 'fighting' | 'won' | 'lost';

export const ELEMENT_EMOJI: Record<string, string> = { '불': '🔥', '물': '💧', '풍': '🍃', '땅': '🪨' };

export const dungeons: DungeonData[] = [
    {
        id: 5,
        name: '깊은 숲',
        levelRange: 'LV 1~10',
        minLevel: 1,
        maxLevel: 10,
        description: '신비로운 숲. 다양한 숲속 생물들이 서식한다',
        monsters: [
            {
                name: '솔잎 다람쥐',
                emoji: '🐿️',
                level: 2,
                hp: 60,
                attack: 10,
                isBoss: false,
                spawnChance: 25,
                imageUrl: "https://rryurpxtarqks8ch.public.blob.vercel-storage.com/superpet/monster/squi.jpg",
                drops: [
                    { itemId: 'feed', chance: 20 },
                    { itemId: 'iron_helmet', chance: 10 },
                    { itemId: 'simple_cloak', chance: 10 },
                ],
            },
            {
                name: '숲속 여우',
                emoji: '🦊',
                level: 4,
                hp: 65,
                attack: 11,
                isBoss: false,
                spawnChance: 22,
                imageUrl: "https://rryurpxtarqks8ch.public.blob.vercel-storage.com/superpet/monster/fox.jpg",
                drops: [
                    { itemId: 'feed', chance: 20 },
                    { itemId: 'iron_helmet', chance: 10 },
                    { itemId: 'leather_armor', chance: 10 },
                ],
            },
            {
                name: '은빛 올빼미',
                emoji: '🦉',
                level: 5,
                hp: 70,
                attack: 12,
                isBoss: false,
                spawnChance: 20,
                imageUrl: "https://rryurpxtarqks8ch.public.blob.vercel-storage.com/superpet/monster/owl.jpg",
                drops: [
                    { itemId: 'feed', chance: 20 },
                    { itemId: 'cloth_gloves', chance: 10 },
                    { itemId: 'simple_cloak', chance: 10 },
                ],
            },
            {
                name: '독버섯 정령',
                emoji: '🍄',
                level: 7,
                hp: 75,
                attack: 13,
                isBoss: false,
                spawnChance: 17,
                imageUrl: "https://rryurpxtarqks8ch.public.blob.vercel-storage.com/superpet/monster/mush.jpg",
                drops: [
                    { itemId: 'armor_enhance_scroll', chance: 2 },
                    { itemId: 'feed', chance: 20 },
                    { itemId: 'running_shoes', chance: 10 },
                    { itemId: 'wooden_shield', chance: 10 },
                ],
            },
            {
                name: '은빛 늑대',
                emoji: '🐺',
                level: 9,
                hp: 80,
                attack: 15,
                isBoss: false,
                spawnChance: 13,
                imageUrl: "https://rryurpxtarqks8ch.public.blob.vercel-storage.com/superpet/monster/wolf.jpg",
                drops: [
                    { itemId: 'weapon_enhance_scroll', chance: 2 },
                    { itemId: 'feed', chance: 20 },
                    { itemId: 'wooden_sword', chance: 10 },
                    { itemId: 'iron_helmet', chance: 10 },
                ],
            },
            {
                name: '숲지기',
                emoji: '🌲',
                level: 10,
                hp: 150,
                attack: 17,
                isBoss: true,
                spawnChance: 5,
                videoUrl: "https://rryurpxtarqks8ch.public.blob.vercel-storage.com/superpet/monster/Forest_Guardian_mov.mp4",
                drops: [
                    { itemId: 'weapon_enhance_scroll', chance: 50 },
                    { itemId: 'armor_enhance_scroll', chance: 50 },
                    { itemId: 'dubai_cookie', chance: 100 },
                    { itemId: 'iron_helmet', chance: 20 },
                    { itemId: 'leather_armor', chance: 20 },
                    { itemId: 'cloth_gloves', chance: 20 },
                    { itemId: 'running_shoes', chance: 20 },
                    { itemId: 'simple_cloak', chance: 20 },
                    { itemId: 'wooden_sword', chance: 20 },
                    { itemId: 'wooden_shield', chance: 20 },
                    { itemId: 'wooden_pendant', chance: 20 },
                    { itemId: 'copper_ring', chance: 20 },
                ],
            },
        ],
    },
    {
        id: 6,
        name: '고요한 호수',
        levelRange: 'LV 11~20',
        minLevel: 11,
        maxLevel: 20,
        description: '고요한 호수. 물밑에서 강력한 힘이 느껴진다',
        monsters: [
            {
                name: '틸라피아',
                emoji: '🐟',
                level: 12,
                hp: 100,
                attack: 40,
                isBoss: false,
                spawnChance: 25,
                imageUrl: "https://rryurpxtarqks8ch.public.blob.vercel-storage.com/superpet/monster/Tilapia.jpg",
                drops: [
                    { itemId: 'feed', chance: 20 },
                    { itemId: 'dubai_cookie', chance: 10 },
                    { itemId: 'silver_necklace', chance: 5 },
                    { itemId: 'silver_ring', chance: 5 },
                ],
            },
            {
                name: '메기',
                emoji: '🐟',
                level: 14,
                hp: 110,
                attack: 42,
                isBoss: false,
                spawnChance: 22,
                imageUrl: "https://rryurpxtarqks8ch.public.blob.vercel-storage.com/superpet/monster/Catfish.jpg",
                drops: [
                    { itemId: 'feed', chance: 20 },
                    { itemId: 'dubai_cookie', chance: 10 },
                    { itemId: 'bronze_helmet', chance: 5 },
                    { itemId: 'chain_armor', chance: 5 },
                ],
            },
            {
                name: '물 뱀',
                emoji: '🐍',
                level: 16,
                hp: 120,
                attack: 44,
                isBoss: false,
                spawnChance: 20,
                imageUrl: "https://rryurpxtarqks8ch.public.blob.vercel-storage.com/superpet/monster/WaterSnake.jpg",
                drops: [
                    { itemId: 'feed', chance: 20 },
                    { itemId: 'dubai_cookie', chance: 10 },
                    { itemId: 'leather_gloves', chance: 5 },
                    { itemId: 'traveler_cloak', chance: 5 },
                ],
            },
            {
                name: '세이렌',
                emoji: '🧜',
                level: 18,
                hp: 110,
                attack: 50,
                isBoss: false,
                spawnChance: 17,
                imageUrl: "https://rryurpxtarqks8ch.public.blob.vercel-storage.com/superpet/monster/Siren.jpg",
                drops: [
                    { itemId: 'armor_enhance_scroll', chance: 2 },
                    { itemId: 'feed', chance: 20 },
                    { itemId: 'dubai_cookie', chance: 10 },
                    { itemId: 'leather_boots', chance: 5 },
                    { itemId: 'iron_shield', chance: 5 },
                ],
            },
            {
                name: '물 정령',
                emoji: '👻',
                level: 19,
                hp: 120,
                attack: 55,
                isBoss: false,
                spawnChance: 13,
                imageUrl: "https://rryurpxtarqks8ch.public.blob.vercel-storage.com/superpet/monster/WaterSpirit.jpg",
                drops: [
                    { itemId: 'weapon_enhance_scroll', chance: 2 },
                    { itemId: 'feed', chance: 20 },
                    { itemId: 'dubai_cookie', chance: 10 },
                    { itemId: 'iron_sword', chance: 5 },
                    { itemId: 'bronze_helmet', chance: 5 },
                ],
            },
            {
                name: '레비아탄',
                emoji: '🐉',
                level: 20,
                hp: 300,
                attack: 60,
                isBoss: true,
                spawnChance: 5,
                videoUrl: "https://rryurpxtarqks8ch.public.blob.vercel-storage.com/superpet/monster/Leviathan_mov.mp4",
                drops: [
                    { itemId: 'weapon_enhance_scroll', chance: 50 },
                    { itemId: 'armor_enhance_scroll', chance: 50 },
                    { itemId: 'dubai_cookie', chance: 100 },
                    { itemId: 'bronze_helmet', chance: 10 },
                    { itemId: 'chain_armor', chance: 10 },
                    { itemId: 'leather_gloves', chance: 10 },
                    { itemId: 'leather_boots', chance: 10 },
                    { itemId: 'traveler_cloak', chance: 10 },
                    { itemId: 'iron_sword', chance: 10 },
                    { itemId: 'iron_shield', chance: 10 },
                    { itemId: 'silver_necklace', chance: 10 },
                    { itemId: 'silver_ring', chance: 10 },
                ],
            },
        ],
    },
    {
        id: 7,
        name: '대지의 균열',
        levelRange: 'LV 21~30',
        minLevel: 21,
        maxLevel: 30,
        description: '대지가 갈라지며 드러난 지하 세계. 용암과 바위 사이로 강력한 존재들이 도사린다',
        monsters: [
            {
                name: '사막 전갈',
                emoji: '🦂',
                level: 22,
                hp: 300,
                attack: 65,
                isBoss: false,
                spawnChance: 25,
                imageUrl: "https://rryurpxtarqks8ch.public.blob.vercel-storage.com/superpet/monster/DesertScorpion.jpg",
                drops: [
                    { itemId: 'feed', chance: 20 },
                    { itemId: 'dubai_cookie', chance: 10 },
                    { itemId: 'ruby_necklace', chance: 3 },
                    { itemId: 'sapphire_ring', chance: 3 },
                ],
            },
            {
                name: '바위 골렘',
                emoji: '🗿',
                level: 24,
                hp: 350,
                attack: 70,
                isBoss: false,
                spawnChance: 22,
                imageUrl: "https://rryurpxtarqks8ch.public.blob.vercel-storage.com/superpet/monster/RockGolem.jpg",
                drops: [
                    { itemId: 'feed', chance: 20 },
                    { itemId: 'dubai_cookie', chance: 10 },
                    { itemId: 'knight_helmet', chance: 3 },
                    { itemId: 'plate_armor', chance: 3 },
                ],
            },
            {
                name: '땅굴 거미',
                emoji: '🕷️',
                level: 26,
                hp: 370,
                attack: 75,
                isBoss: false,
                spawnChance: 20,
                imageUrl: "https://rryurpxtarqks8ch.public.blob.vercel-storage.com/superpet/monster/TunnelSpider.jpg",
                drops: [
                    { itemId: 'feed', chance: 10 },
                    { itemId: 'dubai_cookie', chance: 5 },
                    { itemId: 'steel_gauntlets', chance: 3 },
                    { itemId: 'mage_cloak', chance: 3 },
                ],
            },
            {
                name: '대지 도마뱀',
                emoji: '🦎',
                level: 28,
                hp: 400,
                attack: 80,
                isBoss: false,
                spawnChance: 17,
                imageUrl: "https://rryurpxtarqks8ch.public.blob.vercel-storage.com/superpet/monster/EarthLizard.jpg",
                drops: [
                    { itemId: 'armor_enhance_scroll', chance: 2 },
                    { itemId: 'feed', chance: 10 },
                    { itemId: 'dubai_cookie', chance: 5 },
                    { itemId: 'wind_boots', chance: 3 },
                    { itemId: 'guardian_shield', chance: 3 },
                ],
            },
            {
                name: '거대 땅굴 벌레',
                emoji: '🐉',
                level: 29,
                hp: 420,
                attack: 85,
                isBoss: false,
                spawnChance: 13,
                imageUrl: "https://rryurpxtarqks8ch.public.blob.vercel-storage.com/superpet/monster/GiantTunnelWorm.jpg",
                drops: [
                    { itemId: 'weapon_enhance_scroll', chance: 2 },
                    { itemId: 'feed', chance: 10 },
                    { itemId: 'dubai_cookie', chance: 5 },
                    { itemId: 'katana', chance: 3 },
                    { itemId: 'knight_helmet', chance: 3 },
                ],
            },
            {
                name: '대지의 군주',
                emoji: '🌋',
                level: 30,
                hp: 700,
                attack: 100,
                isBoss: true,
                spawnChance: 5,
                videoUrl: "https://rryurpxtarqks8ch.public.blob.vercel-storage.com/superpet/monster/Earth_Lord_mov.mp4",
                drops: [
                    { itemId: 'weapon_enhance_scroll', chance: 50 },
                    { itemId: 'armor_enhance_scroll', chance: 50 },
                    { itemId: 'dubai_cookie', chance: 100 },
                    { itemId: 'knight_helmet', chance: 5 },
                    { itemId: 'plate_armor', chance: 5 },
                    { itemId: 'steel_gauntlets', chance: 5 },
                    { itemId: 'wind_boots', chance: 5 },
                    { itemId: 'mage_cloak', chance: 5 },
                    { itemId: 'katana', chance: 5 },
                    { itemId: 'guardian_shield', chance: 5 },
                    { itemId: 'ruby_necklace', chance: 5 },
                    { itemId: 'sapphire_ring', chance: 5 },
                ],
            },
        ],
    },
    {
        id: 8,
        name: '피닉스의 둥지',
        levelRange: 'LV 31~40',
        minLevel: 31,
        maxLevel: 40,
        description: '하늘 높이 솟은 화산 꼭대기의 둥지. 불사조의 화염이 모든 것을 태운다',
        monsters: [
            {
                name: '화염 박쥐',
                emoji: '🦇',
                level: 32,
                hp: 600,
                attack: 100,
                isBoss: false,
                spawnChance: 25,
                imageUrl: "https://rryurpxtarqks8ch.public.blob.vercel-storage.com/superpet/monster/ACT_4_FlameBat.jpg",
                drops: [
                    { itemId: 'feed', chance: 40 },
                    { itemId: 'dubai_cookie', chance: 20 },
                    { itemId: 'diamond_necklace', chance: 1 },
                    { itemId: 'emerald_ring', chance: 1 },
                ],
            },
            {
                name: '용암 정령',
                emoji: '🐢',
                level: 34,
                hp: 620,
                attack: 105,
                isBoss: false,
                spawnChance: 22,
                imageUrl: "https://rryurpxtarqks8ch.public.blob.vercel-storage.com/superpet/monster/ACT_4_LavaSpirit.jpg",
                drops: [
                    { itemId: 'feed', chance: 40 },
                    { itemId: 'dubai_cookie', chance: 20 },
                    { itemId: 'phoenix_helmet', chance: 1 },
                    { itemId: 'starlight_armor', chance: 1 },
                ],
            },
            {
                name: '불꽃 하피',
                emoji: '🦅',
                level: 36,
                hp: 650,
                attack: 110,
                isBoss: false,
                spawnChance: 20,
                imageUrl: "https://rryurpxtarqks8ch.public.blob.vercel-storage.com/superpet/monster/ACT_4_FlameHarpy.jpg",
                drops: [
                    { itemId: 'feed', chance: 40 },
                    { itemId: 'dubai_cookie', chance: 20 },
                    { itemId: 'ogre_power_gauntlet', chance: 1 },
                    { itemId: 'shadow_cloak', chance: 1 },
                ],
            },
            {
                name: '화산 기사',
                emoji: '⚔️',
                level: 38,
                hp: 680,
                attack: 115,
                isBoss: false,
                spawnChance: 17,
                imageUrl: "https://rryurpxtarqks8ch.public.blob.vercel-storage.com/superpet/monster/ACT_4_VolcanoKnight.jpg",
                drops: [
                    { itemId: 'armor_enhance_scroll', chance: 5 },
                    { itemId: 'feed', chance: 40 },
                    { itemId: 'dubai_cookie', chance: 20 },
                    { itemId: 'thunder_boots', chance: 1 },
                    { itemId: 'holy_shield', chance: 1 },
                ],
            },
            {
                name: '불의 요정',
                emoji: '🔥',
                level: 39,
                hp: 700,
                attack: 120,
                isBoss: false,
                spawnChance: 13,
                imageUrl: "https://rryurpxtarqks8ch.public.blob.vercel-storage.com/superpet/monster/ACT_4_FireFairy.jpg",
                drops: [
                    { itemId: 'weapon_enhance_scroll', chance: 5 },
                    { itemId: 'feed', chance: 40 },
                    { itemId: 'dubai_cookie', chance: 20 },
                    { itemId: 'shadow_blade', chance: 1 },
                    { itemId: 'phoenix_helmet', chance: 1 },
                ],
            },
            {
                name: '피닉스',
                emoji: '🐦‍🔥',
                level: 40,
                hp: 1200,
                attack: 150,
                isBoss: true,
                spawnChance: 1,
                videoUrl: "https://rryurpxtarqks8ch.public.blob.vercel-storage.com/superpet/monster/Phoenix_mov.mp4",
                drops: [
                    { itemId: 'weapon_enhance_scroll', chance: 100 },
                    { itemId: 'armor_enhance_scroll', chance: 100 },
                    { itemId: 'accessory_enhance_scroll', chance: 100 },
                    { itemId: 'dubai_cookie', chance: 100 },
                    { itemId: 'phoenix_helmet', chance: 5 },
                    { itemId: 'starlight_armor', chance: 5 },
                    { itemId: 'ogre_power_gauntlet', chance: 5 },
                    { itemId: 'thunder_boots', chance: 5 },
                    { itemId: 'shadow_cloak', chance: 5 },
                    { itemId: 'shadow_blade', chance: 5 },
                    { itemId: 'holy_shield', chance: 5 },
                    { itemId: 'phoenix_heart', chance: 5 },
                    { itemId: 'emerald_ring', chance: 5 },
                ],
            },
        ],
    },
    {
        id: 9,
        name: '용의 계곡',
        description: '고대의 용들이 서식하는 위험한 계곡. 강력한 드래곤들이 도사리고 있다',
        levelRange: 'LV 41~50',
        minLevel: 41,
        maxLevel: 50,
        monsters: [
            {
                name: '어린 비룡',
                emoji: '🦎',
                level: 42,
                hp: 800,
                attack: 130,
                isBoss: false,
                spawnChance: 26,
                drops: [
                    { itemId: 'meat', chance: 40 },
                    { itemId: 'dubai_cookie', chance: 20 },
                    { itemId: 'phoenix_helmet', chance: 1 },
                    { itemId: 'starlight_armor', chance: 1 },
                ],
            },
            {
                name: '독룡',
                emoji: '🐍',
                level: 44,
                hp: 850,
                attack: 135,
                isBoss: false,
                spawnChance: 23,
                drops: [
                    { itemId: 'meat', chance: 40 },
                    { itemId: 'dubai_cookie', chance: 20 },
                    { itemId: 'ogre_power_gauntlet', chance: 1 },
                    { itemId: 'thunder_boots', chance: 1 },
                ],
            },
            {
                name: '화염 드레이크',
                emoji: '🔥',
                level: 46,
                hp: 900,
                attack: 140,
                isBoss: false,
                spawnChance: 21,
                drops: [
                    { itemId: 'accessory_enhance_scroll', chance: 5 },
                    { itemId: 'meat', chance: 40 },
                    { itemId: 'dubai_cookie', chance: 20 },
                    { itemId: 'shadow_cloak', chance: 1 },
                    { itemId: 'shadow_blade', chance: 1 },
                ],
            },
            {
                name: '빙결 와이번',
                emoji: '❄️',
                level: 48,
                hp: 950,
                attack: 145,
                isBoss: false,
                spawnChance: 17,
                drops: [
                    { itemId: 'armor_enhance_scroll', chance: 5 },
                    { itemId: 'meat', chance: 40 },
                    { itemId: 'dubai_cookie', chance: 20 },
                    { itemId: 'holy_shield', chance: 1 },
                    { itemId: 'diamond_necklace', chance: 1 },
                ],
            },
            {
                name: '암흑 비룡',
                emoji: '🖤',
                level: 49,
                hp: 1000,
                attack: 150,
                isBoss: false,
                spawnChance: 12,
                drops: [
                    { itemId: 'weapon_enhance_scroll', chance: 5 },
                    { itemId: 'meat', chance: 40 },
                    { itemId: 'dubai_cookie', chance: 20 },
                    { itemId: 'emerald_ring', chance: 1 },
                    { itemId: 'phoenix_helmet', chance: 1 },
                ],
            },
            {
                name: '마룡',
                emoji: '🐲',
                level: 50,
                hp: 2000,
                attack: 200,
                isBoss: true,
                spawnChance: 1,
                videoUrl: "https://rryurpxtarqks8ch.public.blob.vercel-storage.com/superpet/monster/Evil_Dragon_mov.mp4",
                drops: [
                    { itemId: 'weapon_enhance_scroll', chance: 100 },
                    { itemId: 'armor_enhance_scroll', chance: 100 },
                    { itemId: 'accessory_enhance_scroll', chance: 100 },
                    { itemId: 'legend_meat', chance: 100 },
                    { itemId: 'dragon_helmet', chance: 1 },
                    { itemId: 'dragon_armor', chance: 1 },
                    { itemId: 'titan_fists', chance: 1 },
                    { itemId: 'pegasus_boots', chance: 1 },
                    { itemId: 'celestial_cloak', chance: 1 },
                    { itemId: 'excalibur', chance: 1 },
                    { itemId: 'aegis_shield', chance: 1 },
                    { itemId: 'diamond_necklace', chance: 1 },
                    { itemId: 'infinity_ring', chance: 1 },
                ],
            },
        ],
    },
];
